cloudinary/js-transformation-builder-sdk

- package.json
- scripts/build.sh
- scripts/buildDocs.sh
- scripts/injectPackageVersionToDistFiles.ts
- scripts/updateCompliationTests.js
- scripts/updateInjectVersionSemver.js
- src/internal/utils/packageVersion.ts
> Fix broken build

- __TESTS__/unit/fromJson/rotate.fromJson.test.ts
- __TESTS__/unit/toJson/rotate.toJson.test.ts
- src/actions/rotate/RotateAction.ts
- src/internal/fromJson.ts
- src/internal/models/IRotateActionModel.ts
Add from/toJson for rotateByAngle Action
> Add from/toJson for rotateByAngle Action

- __TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
- __TESTS__/unit/fromJson/backgroundRemoval.fromJson.test.ts
- __TESTS__/unit/toJson/backgroundRemoval.toJson.test.ts
- src/actions/effect.ts
- src/actions/effect/BackgroundRemoval.ts
- src/internal/fromJson.ts
- src/internal/models/IEffectActionModel.ts
- src/qualifiers/foregroundObject.ts
Adds new action: https://cloudinary.com/documentation/transformation_reference#e_background_removal
> New Action: AI add-on Background Removal

- src/actions/effect/DropShadow.ts
Update JSDoc info about default values of Drop Shadow action.
> Update info about default values of Drop Shadow action

- __TESTS__/unit/fromJson/adjust.fromJson.test.ts
- src/internal/fromJson.ts
- Add fromJson support to Opacity action
> Add fromJson support to Opacity action

- __TESTS__/unit/fromJson/border.fromJson.test.ts
- __TESTS__/unit/toJson/border.toJson.test.ts
- src/actions/border.ts
- src/internal/models/IBorderActionModel.ts
- Adjust border radius `from/toJson` actionModel (flatten property)
> Adjust border radius from/toJson model

- __TESTS__/unit/fromJson/border.fromJson.test.ts
- __TESTS__/unit/toJson/border.toJson.test.ts
- src/actions/border.ts
- src/internal/models/IBorderActionModel.ts
- Border actionModel params compliant with transformation-model
> Border actionModel params compliant with transformation-model

- __TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
- __TESTS__/unit/actions/Effect.test.ts
- __TESTS__/unit/fromJson/effect.fromJson.test.ts
- __TESTS__/unit/toJson/effect.toJson.test.ts
- src/actions/effect.ts
- src/actions/effect/GenerativeReplace.ts
- src/internal/fromJson.ts
- src/internal/models/IEffectActionModel.ts
- Adds `Effect.generativeReplace()` action
> Generative Replace action support

- __TESTS__/unit/actions/Background.test.ts
- __TESTS__/unit/toJson/resize.toJson.test.ts
- src/actions/resize/ResizePadAction.ts
- src/internal/models/createBackgroundFromModel.ts
- src/qualifiers/background.ts
- src/qualifiers/background/shared/BackgroundGenerativeFillQualifier.ts
`.background(Background.generativeFill().prompt("turtles in the sea"))`
> Standalone generative fill action

- __TESTS__/unit/actions/Effect.test.ts
- __TESTS__/unit/fromJson/effect.fromJson.test.ts
- __TESTS__/unit/toJson/effect.toJson.test.ts
- src/actions/effect.ts
- src/actions/effect/GenerativeRecolor.ts
- src/internal/fromJson.ts
- src/internal/models/IEffectActionModel.ts
- Add a new `generativeRecolor` action
> Generative Recolor effect action

- __TESTS__/unit/actions/Effect.test.ts
- __TESTS__/unit/fromJson/effect.fromJson.test.ts
- __TESTS__/unit/toJson/effect.toJson.test.ts
- src/actions/effect.ts
- src/internal/fromJson.ts
- src/internal/internalConstants.ts
- Add `generativeRestore()` effect action
> Add generativeRestore action

- __TESTS__/unit/actions/Effect.test.ts
- __TESTS__/unit/fromJson/effect.fromJson.test.ts
- __TESTS__/unit/toJson/effect.toJson.test.ts
- src/actions/effect.ts
- src/internal/fromJson.ts
- src/internal/internalConstants.ts
- Add `upscale()` (`e_upscale`) action
> Upscale action support

- __TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
- __TESTS__/unit/fromJson/effect.fromJson.test.ts
- __TESTS__/unit/toJson/effect.toJson.test.ts
- src/actions/effect.ts
- src/actions/effect/Blur.ts
- src/actions/effect/pixelate/Pixelate.ts
- src/internal/fromJson.ts
- src/internal/models/IEffectActionModel.ts
- src/qualifiers/region/CustomRegion.ts
- src/qualifiers/region/NamedRegion.ts
Add model translation to the `Blur` action.
> Add model translation to the blur action

- __TESTS__/unit/actions/Resize/AutoResizeAction.test.ts
- __TESTS__/unit/fromJson/resize.fromJson.test.ts
- __TESTS__/unit/toJson/resize.toJson.test.ts
- src/actions/resize.ts
- src/internal/fromJson.ts
- Add Resize.auto() action
- x ] Tests - Add proper tests to the added code.
> Add resize.auto action

- __TESTS__/unit/actions/Effect.test.ts
- __TESTS__/unit/fromJson/effect.fromJson.test.ts
- __TESTS__/unit/toJson/effect.toJson.test.ts
- src/actions/effect.ts
- src/internal/fromJson.ts
> Add Enhance action

- __TESTS__/unit/actions/Resize/AutoPadResizeAction.test.ts
- __TESTS__/unit/fromJson/resize.fromJson.test.ts
- __TESTS__/unit/toJson/resize.toJson.test.ts
- src/actions/resize.ts
- src/actions/resize/ResizeAutoPadAction.ts
- src/internal/fromJson.ts
- src/internal/internalConstants.ts
- src/internal/models/IResizeAutoPadModel.ts
> Add autoPad resize action

- __TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
- __TESTS__/unit/actions/Overlay.test.ts
- __TESTS__/unit/fromJson/overlayUnderlay.fromJson.test.ts
- __TESTS__/unit/toJson/overlayUnderlay.toJson.test.ts
- src/internal/models/IAudioSourceModel.ts
- src/internal/models/createSourceFromModel.ts
- src/qualifiers/source.ts
- src/qualifiers/source/sourceTypes/AudioSource.ts
- Support `audio()` as new overlay source.
> Support audio as an overlay source

- __TESTS__/unit/fromJson/rotate.fromJson.test.ts
- __TESTS__/unit/toJson/rotate.toJson.test.ts
- src/actions/rotate/RotateAction.ts
- src/internal/fromJson.ts
- src/internal/models/IRotateActionModel.ts
- Add fromJson/toJson support for "rotate by mode"
> Add json conversion for rotate by mode

- __TESTS__/unit/fromJson/adjust.fromJson.test.ts
- __TESTS__/unit/toJson/adjust.toJson.test.ts
- src/actions/adjust.ts
- src/internal/fromJson.ts
- Add internal converter to Sharpen action
> Add internal converter to Sharpen action

- src/qualifiers/flag/FlagQualifier.ts
- Should resolve [Security alert on FlagQualifier](https://github.com/cloudinary/js-transformation-builder-sdk/issues/31) issue
> Security alert on FlagQualifier fix

- __TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
- __TESTS__/unit/fromJson/effect.fromJson.test.ts
- __TESTS__/unit/toJson/effect.toJson.test.ts
- src/actions/effect.ts
- src/actions/effect/Extract.ts
- src/internal/fromJson.ts
- src/internal/models/IEffectActionModel.ts
- src/qualifiers/extractMode.ts
- src/types/types.ts
Add support for extract transformation.
> Add support for extract transformation

- src/internal/models/createBackgroundModel.ts
- src/qualifiers/background/shared/BackgroundGenerativeFillQualifier.ts
Proposal how to simplify https://github.com/cloudinary/js-transformation-builder-sdk/pull/62
> Refactor proposal for gen_fill encoding

- __TESTS_BUNDLE_SIZE__/bundleSizeTestCases.ts
- __TESTS__/unit/actions/Background.test.ts
- __TESTS__/unit/fromJson/effect.fromJson.test.ts
- __TESTS__/unit/toJson/effect.toJson.test.ts
- __TESTS__/unit/toJson/resize.toJson.test.ts
- src/actions/effect/GenerativeBackgroundReplace.ts
- src/internal/models/createBackgroundModel.ts
- src/internal/utils/encodePromptComponents.ts
- src/qualifiers/background/shared/BackgroundGenerativeFillQualifier.ts
Escaping special chars for gen fill and gen background replace transformation.
> gen bg replace, gen fill - handle special chars

- __TESTS__/unit/fromJson/effect.fromJson.test.ts
- __TESTS__/unit/toJson/effect.toJson.test.ts
- __TESTS__/unit/toJson/resize.toJson.test.ts
- src/actions/effect/GenerativeBackgroundReplace.ts
- src/qualifiers/background/shared/BackgroundGenerativeFillQualifier.ts
% char caused error while decoding (it cannot be decoded)
> gen fill, gen bg replace - prevent decode with percentage char

- __TESTS__/unit/fromJson/effect.fromJson.test.ts
- __TESTS__/unit/toJson/effect.toJson.test.ts
- src/actions/effect.ts
- src/actions/reshape/TrimAction.ts
- src/internal/fromJson.ts
- src/internal/models/IImageTrimActionModel.ts
add image trim capability to sdk
https://cloudinary.atlassian.net/browse/IMG-5961
> add image trim to ActionModelMap

- __TESTS__/unit/actions/Reshape.test.ts
- __TESTS__/unit/fromJson/reshape.fromJson.test.ts
- __TESTS__/unit/toJson/reshape.toJson.test.ts
- src/actions/reshape.ts
- src/actions/reshape/Displace.ts
- src/actions/reshape/Distort.ts
- src/actions/reshape/DistortArc.ts
- src/actions/reshape/Shear.ts
- src/actions/reshape/TrimAction.ts
- src/internal/fromJson.ts
- src/internal/models/IDisplaceActionModel.ts
- src/internal/models/IDistortActionModel.ts
- src/internal/models/IDistortArcActionModel.ts
- src/internal/models/IShearActionModel.ts
- Add Displace action
- Add models (fromJson+toJson) for Distort and Shear actions
> Add displace action + models for other reshape actions
