cloudinary/js-transformation-builder-sdk

- __TESTS__/unit/toJson/adjust.toJson.test.ts
- src/actions/adjust/OpacityAdjustAction.ts
- src/internal/models/IOpacityActionModel.ts
Add missing `_actionModel` to the Opacity action.
_(bug reference: ME-4642)_
> Fix opacity action (missing actionModel)

- __TESTS__/unit/fromJson/border.fromJson.test.ts
- __TESTS__/unit/fromJson/roundCorners.fromJson.test.ts
- __TESTS__/unit/toJson/border.toJson.test.ts
- __TESTS__/unit/toJson/roundCorners.toJson.test.ts
- src/actions/border.ts
- src/actions/roundCorners/RoundCornersAction.ts
- src/internal/fromJson.ts
- src/internal/models/IBorderActionModel.ts
- src/internal/models/IRoundCornersActionModel.ts
FYI there's a misalignment in the [transformation-model](https://github.com/CloudinaryLtd/transformation-model/blob/master/build/model/all.json#L6298), where we have two separated actions defined (`roundCorners` and `roundCornersMax`). 
I'm planning to merge them and model the `radius` property to reflect `[number?, number?, number?, number?] | 'max'` type. 
- Add actionModel and fromJson/toJson support to the RoundCorners action
> Align RoundCorners action with the specs

- src/qualifiers/autoFocus.ts
- Add missing named `onFocus` export in `autoFocus` qualifier
> Add missing focusOn export

- __TESTS__/unit/toJson/overlayUnderlay.toJson.test.ts
- src/internal/models/actionToJson.ts
- Adjusts `toJson` behaviour when it comes to unsupported nested transformations. Previously it could return
```
{"actionType":"overlay","source":{"publicId":"sample","sourceType":"image","transformation":{"error":{}}}}
```
So the error was "hidden" inside `source.transformation`. 
After the changes, the error will be returned instead of action data object.
> Return nested transformation errors at the layer action level

- __TESTS__/unit/toJson/backgroundRemoval.toJson.test.ts
- src/actions/effect/BackgroundRemoval.ts
- Default value for background removal's fine edges option.
Before:
```ts
backgroundRemoval().fineEdges(true) // fineEdges: true
backgroundRemoval().fineEdges() // fineEdges: undefined
backgroundRemoval().fineEdges(false) // fineEdges: undefined
backgroundRemoval() // fineEdges: undefined
```
After changes:
```ts
backgroundRemoval().fineEdges(true) // fineEdges: true
backgroundRemoval().fineEdges() // fineEdges: true
backgroundRemoval().fineEdges(false) // fineEdges: false
backgroundRemoval() // fineEdges: undefined
```
> Default value for background removal's fine edges option

- __TESTS__/unit/toJson/backgroundRemoval.toJson.test.ts
- src/actions/effect/BackgroundRemoval.ts
- src/qualifiers/foregroundObject.ts
`ForegroundObject` qualifier (used in Background Removal `hints`) was inconsistent with autogenerated code snippet for this action:
```
import { backgroundRemoval } from "@cloudinary/url-gen/actions/effect";
import { cat, dog, bicycle } from "@cloudinary/url-gen/qualifiers/foregroundObject";
new CloudinaryImage("docs/rmv_bgd/side_cat_dog_orig.png").effect(
backgroundRemoval().hints(cat(), dog(), bicycle())
);
```
This fix keeps backward compatibility with the previous SDK implementation _(to not create breaking changes and still handle `hints([ForegroundObject.CAT, ForegroundObject.DOG])`)_, but adds handling for the common syntax presented in the Cloudinary Docs.
> Fix: Sync BackgroundRemoval hints with autogenerated docs examples

- __TESTS__/unit/fromJson/generativeRemove.fromJson.test.ts
- __TESTS__/unit/toJson/generativeRemove.toJson.test.ts
- src/actions/effect.ts
- src/actions/effect/GenerativeRemove.ts
- src/internal/fromJson.ts
- src/internal/models/IEffectActionModel.ts
It added support for the [e_gen_remove](https://cloudinary.com/documentation/transformation_reference#e_gen_remove) action.
```js
new CloudinaryImage("docs/food.jpg").addAction(
Effect.generativeRemove().prompt("cake")
)
```
> Add support for Generative Remove effect

- src/qualifiers/foregroundObject.ts
Fix alternative syntax for `ForegroundObject` usage (the one utilized internally in our BFF tx converter):
```
new CloudinaryVideo("sample.mp4").effect(
Effect.backgroundRemoval().hints(
>>  ForegroundObject.bird(),
>>  ForegroundObject.cat()
)
).transformation.toJson();
```
> Fix alternative syntax for ForegroundObject

- __TESTS__/unit/toJson/generativeRemove.toJson.test.ts
- src/actions/effect/GenerativeRemove.ts
- src/qualifiers/region.ts
- src/qualifiers/region/NamedRegion.ts
- src/qualifiers/region/RectangleRegion.ts
Simplify API of `GenerativeRemove` effect. Methods `prompts` and `regions` are replaced by `prompt` and `region` that now support array values. Moreover, new qualifier `Region.rectangle`.
```js
// before
Effect.generativeRemove().prompts(["dog", "cat"]) 
// after
Effect.generativeRemove().prompt("dog", "cat")
// before
Effect.generativeRemove().regions([{x: 100, y: 100, width: 400, height: 400}, {...}]) 
// after
Effect.generativeRemove().region(Region.rectangle(100, 100, 400, 400), Region.rectangle(...)) 
```
> simplify API of GenerativeRemove

- __TESTS__/unit/actions/Effect.test.ts
- __TESTS__/unit/fromJson/effect.fromJson.test.ts
- src/actions/effect.ts
- src/actions/effect/GenerativeRecolor.ts
- Fix Generative Recolor `color` formatting when `#hex` is provided
> Generative Recolor color formatting fix

- __TESTS__/unit/fromJson/backgroundRemoval.fromJson.test.ts
- src/actions/effect/BackgroundRemoval.ts
Splits parameters of `BackgroundRemoval` with `;` instead of `:`.
> Fixes parameters delimiter in BackgroundRemoval action

- __TESTS__/unit/actions/Effect.test.ts
- __TESTS__/unit/fromJson/effect.fromJson.test.ts
- __TESTS__/unit/fromJson/generativeRemove.fromJson.test.ts
- __TESTS__/unit/toJson/effect.toJson.test.ts
- __TESTS__/unit/toJson/generativeRemove.toJson.test.ts
- src/actions/effect/GenerativeRecolor.ts
- src/actions/effect/GenerativeRemove.ts
- src/actions/effect/GenerativeReplace.ts
- src/internal/models/IEffectActionModel.ts
* Add `decectMultiple` method to `GenerativeReplace` 
* Add `removeShadow` method to `GenerativeRemove`
* Create `decectMultiple` alias for `GenerativeRecolor#multiple` method  to be compatible with other "generative" actions 
Implements  new parameters for a several generative actions
> Add missing parameters to generative actions

- __TESTS__/unit/actions/VideoEdit.test.ts
- __TESTS__/unit/fromJson/videoEditTrim.fromJson.test.ts
- __TESTS__/unit/toJson/videoEditTrim.toJson.test.ts
- src/actions/videoEdit/TrimAction.ts
- src/internal/models/ITrimActionModel.ts
Fixes bug for "auto" `VideoEdit.trim`.
```typescript
VideoEdit.trim().startOffset("auto") // returns "so_auto" instead of "so_NaN"
VideoEdit.trim().endOffest("auto") // returns "eo_auto" instead of "eo_NaN"
```
> Add support for "auto" offsets in VideoEdit.trim

- __TESTS__/unit/fromJson/backgroundColor.fromJson.test.ts
- __TESTS__/unit/toJson/backgroundColor.toJson.test.ts
- __TESTS__/unit/toJson/overlayUnderlay.toJson.test.ts
- src/actions/background/actions/BackgroundColor.ts
- src/internal/fromJson.ts
- src/internal/models/IBackgroundColorActionModel.ts
- src/internal/models/IEffectActionModel.ts
- Add color mapping to properly map hex colors, e.g. `colorBackground('#00FFFF')` into `rgb:00FFFF`
- Add missing internal utilities (`fromJson`, `toJson`)
> Add color mapping and missing internals in backgroundColor

- __TESTS__/unit/toJson/backgroundColor.toJson.test.ts
- src/transformation/Transformation.ts
- Ensure the same color mapping in `toJson` regardless of syntax version
> Make bgColor mapping bulletproof regardless of syntax version

- __TESTS__/unit/actions/Background.test.ts
- __TESTS__/unit/fromJson/resize.fromJson.test.ts
- src/internal/models/createBackgroundFromModel.ts
- src/qualifiers/background/shared/BlurredBackgroundAction.ts
- For the SDK usage - fix case with applying only `brightness` property to the blurred background 
(it was assigned to `intensity` param in the URL syntax)
- For the `fromJson` internal utility - always include both params in the returned URL 
_(for static default values in the Builder)_
> Fix blurred background default params handling

- .gitignore
- __TESTS__/unit/actions/Effect.test.ts
- __TESTS__/unit/fromJson/effect.fromJson.test.ts
- __TESTS__/unit/toJson/effect.toJson.test.ts
- src/actions/effect.ts
- src/actions/effect/GenerativeBackgroundReplace.ts
- src/internal/fromJson.ts
- src/internal/models/IEffectActionModel.ts
Add support for generative background replace.
> Add support for generative background replace

- src/internal/fromJson.ts
Fixed import of `GenerativeBackgroundReplace`.
> generative background replace action, fix import

- src/internal/models/IEffectActionModel.ts
Fix for the [issue](https://github.com/cloudinary/js-transformation-builder-sdk/issues/58) where a relative path to the types was missing.
> Fix path to ExtractModeType

- __TESTS__/unit/values/gravity/Gravity.test.ts
- src/qualifiers/autoFocus.ts
- Allow usage of strings in `autoFocus.focusOn` qualifier _(issue ref.: `SNI-8237`)_
> Allow usage of strings in autoFocus.focusOn

- __TESTS__/unit/fromJson/effect.fromJson.test.ts
- __TESTS__/unit/fromJson/extract.fromJson.test.ts
- __TESTS__/unit/toJson/effect.toJson.test.ts
- __TESTS__/unit/toJson/extract.toJson.test.ts
- src/actions/effect/Extract.ts
- src/internal/models/IEffectActionModel.ts
Add support for `preserve-alpha` attribute in `e_extract` action
> Add support for preserve-alpha attribute in e_extract
